### ISSUE TITLE
It's unable to reflect changed tree structure

### ISSUE THREAD

**Issue by unsu0707** [nogahighland/confluence-better-pagetree#9]
It seems that cannot reflect changed tree structure if user changed or move docs to new parent page.

**Comment by kisshy0601** [comment]
Thank you for reporting the problem. Actually this is an expected behaviour so far.
Because the tree data is cached for 10 minutes, structure changes within 10 minutes are not reflected as soon as possible.

https://github.com/nogahighland/confluence-better-pagetree/blob/master/src/scripts/app.vue#L48

For future improvements, my idea is to put a refresh button like below next to search box.
<img src="https://user-images.githubusercontent.com/19767299/76915689-86763900-6901-11ea-8407-616df8d3493d.png" width=30 />
